### ISSUE TITLE
Crear API. Usar Heroku

### ISSUE THREAD

**Issue by edvilme** [ricardoskewes/PhysTrainer#19]
Para hacer bien lo que estamos intentando hacer, es mejor mover gran parte de la lógica de negocio (cómo recuperamos las preguntas, cuáles son los tests de validación, etc) al backend. Para eso es necesario hacer un servidor web. 
1. Propongo usar Node.js porque #javascript xd. Podemos usar Heroku para que corra en una nube virtual.
2. Si ya vamos a usar un servidor web en Heroku, podemos hacer que los archivos HTML se envíen desde ahí. Podemos de una vez mover todo desde Github pages a Heroku
3. Heroku busca un package.json entonces **tendríamos que hacer cambios importantes a la estructura del repo**

@ricardoskewes Tú dime qué opinas. Yo creo que es un buen approach, y tendré cuidado de que no se borre nada de lo que ya teníamos pero si me gustaría que me dieras permiso antes jejeje. 

Salu2, no sé cuando leas esto 🤓

**Comment by edvilme** [comment]
Comunmente la estructura que se usa es:
```
|-- src
|     `-- routes
|-- public
|     |-- img
|     `-- components
|-- schemas
`-- phystrainer

**Comment by edvilme** [comment]
Propongo tambien eliminar los directorios viejos que ya no usamos

**Comment by edvilme** [comment]
https://phystrainer.herokuapp.com/

**Comment by ricardoskewes** [comment]
De acuerdo amigo Eduardo Villalpando.

**Comment by edvilme** [comment]
gracias amigo skewes
